# Generated by Django 5.1.3 on 2025-01-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0002_alter_ensemble_organization_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='compilation',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyricist',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='publisher',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.CharField(max_length=60),
        ),
    ]
